language: python

python:
  - 3.5
  - 3.6

env:
  - DJANGO_VERSION=1.11
  - DJANGO_VERSION=2.0
  - DJANGO_VERSION=2.1
install:
  - pip install Django==$DJANGO_VERSION
  - python setup.py install

script:
  - python -m unittest

notifications:
  slack: squalex:oeMbtSBTTHv2sgjXB3DsbJpY