language: python

python:
  - 3.5
  - 3.6

env:
  - DJANGO_VERSION=2.0
  - DJANGO_VERSION=2.1
  - DJANGO_VERSION=2.2

install:
  - pip install Django==$DJANGO_VERSION
  - pip setup.py install

script:
  - python -m unittest