language: python

python:
  - 3.0
  - 3.1
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - 3.6
  - 3.7

env:
  - DJANGO_VERSION=1.10
  - DJANGO_VERSION=2
  - DJANGO_VERSION=2.1

install:
  - pip install Django==$DJANGO_VERSION
  - pip install -e .[dev]

script:
  - py.test